# Generated by Django 5.0.6 on 2024-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_fuelstation_gas_final_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_tanks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
