# Generated by Django 5.0.6 on 2024-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_fuelstation_gasoline_tanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='control_period',
            field=models.CharField(choices=[('start', 'ابتدا دوره'), ('end', 'انتهای دوره')], max_length=50, verbose_name='انتخاب دوره'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='diesel_electronic_sales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار فروش الکترونیکی گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_final_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='موجودی انتهای دوره گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_initial_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی اول دوره گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_nozzles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد نازل های گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_received',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار رسیده دوره گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_tank1_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی مخزن شماره ۱ گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_tank2_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی مخزن شماره ۲ گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gas_tanks',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مخازن گاز'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_electronic_sales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار فروش الکترونیکی بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_final_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='موجودی انتهای دوره بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_initial_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی اول دوره بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_nozzles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد نازل های بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_received',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار رسیده دوره بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_tank1_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی مخزن شماره ۱ بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_tank2_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی مخزن شماره ۲ بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='gasoline_tanks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد مخزن های بنزین'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم جایگاه'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='product_type',
            field=models.CharField(choices=[('gasoline', 'بنزین'), ('diesel', 'نفتگاز'), ('both', 'هر دو')], max_length=50, verbose_name='انتخاب محصول'),
        ),
    ]
