# Generated by Django 5.0.6 on 2024-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_fuelstation_control_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='diesel_electronic_samane_sales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار فروش الکترونیکی سامانه گاز'),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='gasoline_electronic_samane_sales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار فروش الکترونیکی سامانه بنزین'),
        ),
    ]
