# Generated by Django 5.0.6 on 2024-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_fuelstation_diesel_electronic_samane_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstation',
            name='gas_tank1_stock',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='gas_tank2_stock',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='gasoline_tank1_stock',
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='gasoline_tank2_stock',
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='control_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='پایان دوره'),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='control_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='شروع دوره'),
        ),
    ]
